#!/usr/bin/python3


# See https://xapian.org/docs/bindings/python/examples.html

import sys
import xapian

if len(sys.argv) != 2:
    print("Usage: %s PATH_TO_DATABASE" % (sys.argv[0]), file=sys.stderr)
    sys.exit(1)

# Open the database for update, creating a new database if necessary.
database = xapian.WritableDatabase(sys.argv[1], xapian.DB_CREATE_OR_OPEN)

indexer = xapian.TermGenerator()
stemmer = xapian.Stem("english")
indexer.set_stemmer(stemmer)

record = {}

for line in sys.stdin:

    line = line[:-1]

    if line != "":

        # Accumulate fields
        (key, value) = line.split(": ", 2)
        record[key] = value

    else:

        # Add the document to the index

        doc = xapian.Document()

        # Stored document, containing the verbatim copy
        doctext = "\n".join(["%s: %s" % (k,v) for (k, v) in record.items()])
        doc.set_data(doctext)

        indexer.set_document(doc)

        # Text of field values only, which is what's indexed
        alltext = " ".join([v for (k, v) in record.items()])
        indexer.index_text(alltext)

        database.add_document(doc)

        # Reset for the next one
        record = {}
